version: "3"

services:
  worker:
    build: .
    command: bundle exec sidekiq
    env_file:
      - .env
    environment:
      - RAILS_ENV=production
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - redis
