default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: <%= Rails.application.credentials.dig(:database, :name) %>_dev
  username: <%= Rails.application.credentials.dig(:database, :username) %>
  password: <%= Rails.application.credentials.dig(:database, :password) %>
  host: localhost
  port: 5432
  redis_url: <%= Rails.application.credentials.dig(:redis, :url) %>

test:
  <<: *default
  database: pretty_wayback_test
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  redis_url: redis://localhost:6379/0

production:
  <<: *default
  database: <%= Rails.application.credentials.dig(:database, :name) %>_production
  username: <%= Rails.application.credentials.dig(:database, :username) %>
  password: <%= Rails.application.credentials.dig(:database, :password) %>
  host: <%= Rails.application.credentials.dig(:database, :host) %>
  redis_url: <%= Rails.application.credentials.dig(:redis, :url) %>
